name: Terraform CI

on:
  pull_request:
    paths:
      - 'infra/terraform/**'
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - 'infra/terraform/**'

permissions:
  id-token: write
  contents: read

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: true

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terraform Init
        run: |
          terraform init -input=false -reconfigure \
            -backend-config=bucket=${{ secrets.TF_STATE_BUCKET }} \
            -backend-config=key=${{ secrets.BUCKET_KEY}} \
            -backend-config=region=${{ secrets.AWS_REGION }} \
            -backend-config=dynamodb_table=${{ secrets.TF_STATE_LOCK_TABLE }} \
            -backend-config=encrypt=true

      - name: Terraform Fmt Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: |
          terraform apply -target=module.eks -auto-approve
          terraform plan -input=false -no-color -out .tfplan

      - name: Save Plan Text
        run: terraform show -no-color .tfplan > plan.txt
